backend/controllers/SiteProductController.php
<?php

namespace backend\controllers;

use common\models\Section;
use common\models\SiteSection;
use Yii;
use common\models\Product;
use common\models\ProductSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * SiteProductController implements the CRUD actions for Product model.
 */
class SiteProductController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [''],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'change-parent', 'link-products'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $catName = "";

        $currentSectionID = 0;

        if(!empty($_REQUEST["ProductSearch"]["site_section"])){
            $cat = SiteSection::find()->where(['id' => $_REQUEST["ProductSearch"]["site_section"]])->one();

            if(!empty($cat)){
                $currentSectionID = $cat->id;
                $catName = $cat->name;
            }
        }else{
            $dataProvider->query->andWhere(['>', 'site_section', 0]);
        }

        $siteSections = SiteSection::getSectionListForSelect();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'catName' => $catName,
            'siteSections' => $siteSections,
            'currentSectionID' => $currentSectionID,
        ]);
    }

    public function actionChangeParent($productID, $newParentID){
        Yii::$app->response->format = Response::FORMAT_JSON;

        $product = Product::findOne((int)$productID);

        if(empty($product)){
            return ["success" => false, "message" => "Указан некорректный ID товара"];
        }

        $section = SiteSection::findOne($newParentID);

        if(empty($section)){
            return ["success" => false, "message" => "Указан некорректный ID нового раздела"];
        }

        $product->site_section = $section->id;

        if($product->save()){
            return ["success" => true];
        }else{
            return ["success" => false, "message" => "Произошла ошибка во время сохранения данных"];
        }
    }

    public function actionLinkProducts(){
        Yii::$app->response->format = Response::FORMAT_JSON;

        if(empty($_POST["ids"])){
            return ['success' => false, 'message' => 'Не указаны ID товаров для перемещения'];
        }

        if(empty($_POST['toSection'])){
            return ['success' => false, 'message' => 'Не указан ID нового раздела'];
        }

        $section = SiteSection::findOne((int)$_POST['toSection']);

        if(empty($section)){
            return ['success' => false, 'message' => 'Указан некорректный ID нового раздела'];
        }

        Product::updateAll(['site_section' => $section->id], 'id IN (' . $_POST['ids'] . ')');

        return ['success' => true, "count" => count(explode(",", $_POST['ids'])), "category_name" => $section->name];
    }
}

backend/views/site-product/_search.php
<?php

use common\models\ProductSearch;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?
    $sections = \common\models\SiteSection::getSectionsTree();
    $sectionList = \common\models\SiteSection::getFormatedListForMenu($sections);

    ?>

    <h4>Категория</h4>
    <div class="list_of_cats">
        <?=$sectionList?>
    </div>

    <?php  echo $form->field($model, 'site_section')->hiddenInput()->label(false) ?>

    <?php ActiveForm::end(); ?>

</div>

backend/views/site-product/index.php
<?php

use common\models\ProductSearch;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\View;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $catName string */
/* @var $siteSections [] */
/* @var $currentSectionID int */

$this->registerJsFile("js/jquery-2.2.4.min.js", ['position' => View::POS_HEAD]);
$this->registerJsFile("js/jquery-ui-1.9.2.custom.min.js", ['position' => View::POS_HEAD]);

$this->title = 'Список товаров для выгрузки на сайт';

$this->params['breadcrumbs'][] = ["label" => $this->title, "url" => \yii\helpers\Url::to(['site-product/index'])];

if(!empty($catName)){
    $this->title .= " - " . $catName;
    $this->params['breadcrumbs'][] = $catName;
}

?>

<script>
    var jq2 = jQuery.noConflict();
</script>

<div class="product-index container">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-md-3">
            <?echo $this->render("_search", ['model' => $searchModel])?>
        </div>
        <div class="col-md-9">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    [
                        'class' => 'yii\grid\CheckboxColumn',
                        'name' => 'id'
                    ],
                    'id',
                    'name',
                    'manufacturer_number',
                    'article',
                    //'class_key',
                    //'site_section',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>

        <div class="col-md-12 mb-30">
            <div style="float:right;" class="btn btn-success" data-toggle="modal" data-target="#link_products">Перенести выбранные товары в другой раздел</div>
        </div>
    </div>

</div>

<?= $this->render('/modals/link-product', ['siteSections' => $siteSections]) ?>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        initDrangDropProducts('<?=\yii\helpers\Url::to(['site-product/change-parent'])?>');
    });
</script>